# Generated by Django 3.1.5 on 2021-06-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210608_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('department', models.CharField(default='Cardiologist', max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
